src/Entity/Orders.php
<?php

/*
 * (c) Sven Nolting, 2023
 */

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: "App\Repository\OrdersRepository")]
class Orders
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\Column(type: UuidType::NAME)]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private Uuid $id;

    #[ORM\Column(type: 'string', length: 1000, nullable: false, options: ['default' => ''])]
    private string $note = '';

    #[ORM\Column(type: 'date', nullable: false)]
    private \DateTime $for_date;

    #[ORM\Column(type: 'datetime', nullable: false)]
    private \DateTime $created;

    #[ORM\Column(type: 'string', length: 255, nullable: false)]
    #[Assert\NotBlank(message: 'Bitte gib einen Namen ein.')]
    private string $orderedby = '';

    #[ORM\ManyToOne(targetEntity: Hirsch::class)]
    #[ORM\JoinColumn(nullable: false)]
    private Hirsch $hirsch;

    public function __construct()
    {
        $this->id = Uuid::v7();
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(string $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getForDate(): ?\DateTime
    {
        return $this->for_date;
    }

    public function setForDate(\DateTime $forDate): self
    {
        $this->for_date = $forDate;

        return $this;
    }

    public function getCreated(): ?\DateTime
    {
        return $this->created;
    }

    public function setCreated(\DateTime $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getOrderedby(): ?string
    {
        return $this->orderedby;
    }

    public function setOrderedby(string $orderedby): self
    {
        $this->orderedby = $orderedby;

        return $this;
    }

    public function getHirsch(): ?Hirsch
    {
        return $this->hirsch;
    }

    public function setHirsch(Hirsch $hirsch): self
    {
        $this->hirsch = $hirsch;

        return $this;
    }
}

src/Entity/Paypalmes.php
<?php

/*
 * (c) Sven Nolting, 2023
 */

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: "App\Repository\PaypalmesRepository")]
class Paypalmes
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\Column(type: UuidType::NAME)]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private Uuid $id;

    #[Assert\Regex("/https:\/\/paypal.me\/[\w]*$/", message: 'paypal.link.invalid')]
    #[ORM\Column(type: 'string', length: 100, nullable: false)]
    private string $link;

    #[ORM\Column(type: 'string', length: 100, nullable: false, options: ['default' => ''])]
    private string $name = '';

    #[Assert\Email(message: 'paypal.email.invalid')]
    #[ORM\Column(type: 'string', length: 255, nullable: true, options: ['default' => 'NULL'])]
    private ?string $email = 'NULL';

    #[ORM\Column(type: 'date', nullable: true)]
    private ?\DateTime $bar;

    public function __construct(?Uuid $id = null)
    {
        $this->id = $id ?? Uuid::v7();
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function getLink(): ?string
    {
        return rtrim(trim($this->link), '/');
    }

    public function setLink(string $link): self
    {
        // make sure there is no trailing slash
        $link = rtrim(trim($link), '/');
        $this->link = $link;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getBar(): ?\DateTime
    {
        return $this->bar;
    }

    public function setBar(?\DateTime $bar): self
    {
        $this->bar = $bar;

        return $this;
    }

    public function getBarOnly(): bool
    {
        return null !== $this->bar && $this->bar >= new \DateTime();
    }
}

src/Form/OrderType.php
<?php

/*
 * (c) Sven Nolting, 2023
 */

namespace App\Form;

use App\Entity\Orders;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('orderedby', TextType::class, [
                'row_attr' => ['class' => 'input text required label-large on-surface-text'],
                'attr' => ['placeholder' => 'Max Mustermann', 'class' => 'on-surface-text'],
                'label' => 'Dein Name',
            ])
            ->add('note', TextType::class, [
                'row_attr' => ['class' => 'input text label-large on-surface-text'],
                'attr' => ['placeholder' => 'Keine', 'list' => 'wishlist', 'autofill' => 'off', 'autocomplete' => 'off', 'class' => 'on-surface-text'],
                'required' => false,
                'label' => 'Sonderwünsche',
                'help' => 'Extrawünsche, wie "extra Pommes" oder "ohne Salat"',
                'empty_data' => '',
            ])
            ->add('submit', SubmitType::class, [
                'row_attr' => ['class' => 'submit label-large on-surface-text'],
                'attr' => ['class' => 'btn primary on-primary-text body-medium'],
                'label' => 'Verbindlich bestellen',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Orders::class,
            'for_date' => null,
        ]);
    }
}

src/Controller/OrderController.php
<?php

/*
 * (c) Sven Nolting, 2023
 */

namespace App\Controller;

use App\Entity\Orders;
use App\Entity\Payhistory;
use App\Form\OrderType;
use App\Repository\HirschRepository;
use App\Repository\OrdersRepository;
use App\Repository\PayhistoryRepository;
use App\Repository\PaypalmesRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class OrderController extends AbstractController
{
    #[Route('/order/{preorder}/{slug}', name: 'order', methods: ['GET', 'POST'])]
    public function index(
        int $preorder,
        string $slug,
        HirschRepository $hirschRepository,
        PayhistoryRepository $payhistoryRepository,
        PaypalmesRepository $paypalmesRepository,
        Request $request,
        ManagerRegistry $doctrine,
        MessageBusInterface $bus,
        TranslatorInterface $translator
    ): Response {
        $order = new Orders();
        $hirsch = $hirschRepository->findOneBy(['slug' => $slug]);

        if (null === $hirsch) {
            return $this->redirectToRoute('menu');
        }

        $preorder_time = (new DateTime("+$preorder day"))
            ->setTimezone(new \DateTimeZone('Europe/Berlin'))
            ->setTime(0, 0);
        $order->setCreated((new DateTime())
            ->setTimezone(new \DateTimeZone('Europe/Berlin')))
            ->setForDate($preorder_time)
            ->setHirsch($hirsch);

        if ($request->cookies->get('ordererName') && null === $order->getOrderedby()) {
            $order->setOrderedby($request->cookies->get('ordererName', ''));
        }
        $form = $this->createForm(OrderType::class, $order, [
                'for_date' => $order->getForDate()?->format('d.m.Y') ?? (new \DateTime('now'))->format('d.m.Y'),
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $order = $form->getData();
            $em = $doctrine->getManager();
            $response = new RedirectResponse($this->generateUrl('paynow'));

            if ($order instanceof Orders) {
                if (DateTime::createFromFormat('U', time().'') > DateTime::createFromFormat('H:i', '10:56') && 0 === $preorder) {
                    $activePayer = $this->getActivePayer($paypalmesRepository, $payhistoryRepository, $translator);

                    $this->addFlash('error', $translator->trans('order.search_alternative', ['%orderer%' => $activePayer]));

                    return new RedirectResponse($this->generateUrl('menu'));
                }
                $em->persist($order);
                $em->flush();

                // Set ordererName Cookie
                $cookie = new Cookie(
                    'ordererName',
                    $order->getOrderedby(),
                    (new DateTime('+1 year'))->setTimezone(new \DateTimeZone('Europe/Berlin'))
                );

                // create response with cookie
                $response->headers->setCookie($cookie);

                $this->addFlash('raw', sprintf("<script>window.order_id = '%s'</script>", $order->getId()));
            }

            return $response;
        }

        // if its after 10:55 redirect back to menu
        if (0 === $preorder && DateTime::createFromFormat('U', time().'') > DateTime::createFromFormat('H:i', '10:55')) {
            $activePayer = $this->getActivePayer($paypalmesRepository, $payhistoryRepository, $translator);

            $this->addFlash(
                'warning',
                $translator->trans('order.search_alternative', ['%orderer%' => $activePayer])
            );

            return $this->redirectToRoute('menu');
        }

        $this->addFlash('raw', sprintf("<script>window.gericht = '%s'</script>", $hirsch->getName()));

        return $this->renderForm('order/index.html.twig', [
            'form' => $form,
            'meal' => $hirsch,
            'order_date' => $preorder_time,
        ], new Response(null, $form->isSubmitted() ? 422 : 200));
    }

    #[Route('/order-until', name: 'order-until', methods: ['GET'])]
    public function orderuntil(TranslatorInterface $translator): Response
    {
        return new Response($translator->trans('order.until'), 200);
    }

    #[Route('/orders/delete/{id}', name: 'order_delete', methods: ['GET', 'DELETE'])]
    public function delete(Orders $order, EntityManagerInterface $entityManager, TranslatorInterface $translator): Response
    {
        if (DateTime::createFromFormat('U', time().'') >= DateTime::createFromFormat('H:i', '11:00')) {
            $this->addFlash('error', $translator->trans('order.delete.failedLate'));

            return $this->redirectToRoute('menu');
        }
        $entityManager->remove($order);
        $entityManager->flush();

        $this->addFlash('success', $translator->trans('order.delete.success'));

        return $this->redirectToRoute('orders');
    }

    #[Route('/api/orders/{onlyToday?1}', name: 'api_orders', methods: ['GET'])]
    public function api_orders(Request $request, OrdersRepository $ordersRepository, bool $onlyToday = true): Response
    {
        $orders = $ordersRepository->findAll();
        $data = [];
        foreach ($orders as $order) {
            if (!$onlyToday || ($order->getForDate() && $order->getForDate()->format('Y-m-d') === (new DateTime())->format('Y-m-d'))) {
                $data[] = [
                    'id' => $order->getId(),
                    'orderedby' => $order->getOrderedby(),
                    'created' => $order->getCreated(),
                    'forDate' => $order->getForDate(),
                    'note' => $order->getNote(),
                    'ordered' => $order->getHirsch()?->getName(),
                    'orderedSlug' => $order->getHirsch()?->getSlug(),
                ];
            }
        }

        $frameId = $request->headers->get('Turbo-Frame');
        if (null === $frameId) {
            return new JsonResponse($data);
        }
        $orders = [];
        foreach ($data as $d) {
            $orders[$d['ordered']][$d['note']] = ($orders[$d['ordered']][$d['note']] ?? 0) + 1;
        }
        $rows = 1;
        foreach ($orders as $order => $notes) {
            foreach ($notes as $note => $amount) {
                /* @var string $note */
                ++$rows;

                if (strlen($note) > 0) {
                    ++$rows;
                }
            }
        }

        if ('orders_area' == $frameId) {
            return $this->render('order/orders_textarea.html.twig', [
                'orders' => $orders,
                'rows' => $rows,
            ]);
        }

        return new Response(null, Response::HTTP_BAD_REQUEST);
    }

    #[Route('/bestellungen/', name: 'orders', methods: ['GET'])]
    public function orders(Request $request, EntityManagerInterface $entityManager, PayhistoryRepository $payhistoryRepository): Response
    {
        $preorders = $entityManager
            ->getRepository(Orders::class)
            ->createQueryBuilder('o')
            ->select('o.for_date')
            ->addSelect('o.note')
            ->addSelect('count(o.id) as cnt')
            ->addSelect('count(o.orderedby) as personen')
            ->innerJoin('o.hirsch', 'h')
            ->addSelect('h.name')
            ->where('o.for_date > :date')
            ->groupBy('h.name')
            ->addGroupBy('o.note')
            ->orderBy('o.for_date', 'ASC')
            ->setParameter('date', strftime('%Y-%m-%d'))
            ->getQuery()
            ->getResult();
        $orderNameList = $entityManager
            ->getRepository(Orders::class)
            ->createQueryBuilder('o')
            ->select('o.orderedby')
            ->addSelect('o.id')
            ->addSelect('o.note')
            ->innerJoin('o.hirsch', 'h')
            ->addSelect('h.name')
            ->where('o.for_date = :date')
            ->setParameter('date', strftime('%Y-%m-%d'))
            ->getQuery()
            ->getResult();

        $drawn = null;

        $activePayer = $payhistoryRepository->findActivePayer();
        $cache = new FilesystemAdapter();
        $drawn = $cache->getItem('spinthewheel')->get();

        return $this->render('order/orders.html.twig', [
            'preorders' => $preorders,
            'orderNameList' => $orderNameList,
            'ordererName' => $request->cookies->get('ordererName'),
            'drawn' => $drawn,
            'activePayer' => $activePayer,
        ]);
    }

    #[Route('/zahlen-bitte/', name: 'paynow', methods: ['GET', 'POST'])]
    public function paynow(
        Request $request,
        EntityManagerInterface $entityManager,
        PaypalmesRepository $paypalmesRepository,
        PayhistoryRepository $payhistoryRepository
    ): Response {
        if ($request->isMethod('POST')) {
            $payhistory = new Payhistory();
            $payhistory->setCreated(new DateTime());
            $paypalme = $paypalmesRepository->findOneBy(['id' => $request->request->get('id')]);
            $payhistory->setPaypalme($paypalme);
            $payhistory->setClickedBy($request->cookies->get('ordererName') ?? '');

            $entityManager->persist($payhistory);
            $entityManager->flush();

            // redirect to paypalme.link
            return $this->redirect(($paypalme?->getLink() ?? 'https://paypal.me/rindulalp').'/'.(3.5 + max(0, (float) $request->request->get('tip'))));
        }

templates/order/index.html.twig
{% extends 'base.html.twig' %}
{% block metas %}
    <meta name="turbo-cache-control" content="no-preview">
{% endblock %}

{% block title %}{{ 'order.ordering'|trans }}{% endblock %}

{% block body %}
    <h2 class="title-large on-primary-container-text">{{meal.name}}</h2>
    <small class="label-small on-primary-container-text">{{ 'order.order_date'|trans }} {{order_date|format_datetime('long', 'none', locale='de')}}</small>
    <br>
    <br>
    {{form(form)}}

    <datalist id="wishlist">
        <option value="+ Pommes"></option>
        <option value="+ Senf"></option>
        <option value="+ Mayonnaise"></option>
        <option value="+ Ketchup"></option>
        <option value="Extra Soße"></option>
    </datalist>
{% endblock %}

templates/order/orders.html.twig
{% extends 'base.html.twig' %}
{% block metas %}
    <meta name="turbo-cache-control" content="no-preview">
{% endblock %}

{% block title %}{{ 'order.orders'|trans }}{% endblock %}

{% block body %}
    <h2 class="display-small on-surface-text">{{ 'order.todays_orders'|trans }}</h2>

    <label>
        <turbo-frame id="orders_area" src="{{path('api_orders')}}">
            <textarea class="orderarea on-surface-text" rows="1" readonly="" id="orders">{{ 'order.loading_orders'|trans }}</textarea>
        </turbo-frame>
    </label>
    {% if drawn %}
        <h1 class="error-text headline-medium">{{ drawn }} wurde ausgelost das Essen vom Hirsch abzuholen.</h1>
    {% else %}
        <button class="btn primary-container on-primary-container-text" onclick="document.getElementById('generalModalFrame').setAttribute('src', '{{ path('app_draw') }}'); document.getElementById('generalModal').classList.add('active')">
            Abholer auslosen
        </button>
        <br>
        <br>
    {% endif %}
    <button class="accordion" data-controller="accordion">
        {{ 'order.order_persons'|trans }} ({{ orderNameList | length }})
    </button>

    <div class="panel">
        {% for order in orderNameList %}
        <div class="displayName body-medium on-surface-text">
            <span>
                <span
                    class="material-icons primary-text"
                    style="cursor: pointer;"
                    {{ stimulus_controller('orderdisplay', {
                        name: order.orderedby,
                        ordered: order.name,
                        special: order.note
                    }) }}>
                    restaurant
                </span>

                {{ order.orderedby }}

                {% if order.orderedby == ordererName %}
                    <a href="{{path("order_delete", {id: order.id})}}" class="material-icons btn secondary-text">
                        delete_forever
                    </a>
                {% endif %}
            </span>
        </div>
        {% endfor %}
    </div>

    {% if preorders | length > 0 %}
        <button class="accordion" data-controller="accordion">
            {{ 'order.pre_orders'|trans }} ({{ preorders | length }})
        </button>

        <div class="panel body-medium on-surface-text">
            {% for order in preorders %}
                <h2>{{ order.for_date|format_datetime('long', 'none', locale='de') }}</h2>{{ order.cnt }}x {{ order.name }}
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

templates/order/orders_textarea.html.twig
<turbo-frame id="orders_area">
    <textarea class="orderarea on-surface-text" rows="{{rows}}" readonly="" onclick="this.focus();this.select()" id="orders">
{% for menu, notes in orders %}{% for note, amount in notes %}{{amount}}x {{menu}}
{% if note %}Sonderwunsch: {{note}}
{% endif %}

{% endfor %}{% else %}--- Keine Bestellugen ---{% endfor %}</textarea>
</turbo-frame>

templates/order/paynow.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'pay.pay'|trans }}{% endblock %}

{% block body %}
    <h2 class="title-large on-surface-text">{{  'pay.paypalierer'|trans }}</h2>

    <form method="POST" data-turbo="false">
        <div class="range-slider" data-controller="tipslider">
            <h4 class="title-medium on-surface-text">{{ 'pay.tip'|trans }}:</h4>

            <input
                max="5"
                min="0"
                name="tip"
                step="0.1"
                type="range"
                class="range-slider__range"
                value="0.5"
                data-tipslider-target="input">

            <span class="range-slider__value label-large" data-tipslider-target="display"></span>
        </div>

        {% for paypalme in paypalmes %}
            <div class="paypalmeslistitemcontainer">
                <div class="paypalmeslistitem{% if paypalme.id == active %} active{% endif %}">
                    <button
                        value="{{ paypalme.id }}"
                        name="id"
                        type="submit"
                        formtarget="_blank"
                        class="paypalmebutton body-medium"
                        onclick="setTimeout(() => Turbo.visit('.'), 5000)"
                    >
                        {{paypalme.name}}
                    </button>
                </div>

                {% if paypalme.barOnly %}
                    <span class="label red">
                        {{ 'pay.cash_only'|trans }}
                    </span>
                {% endif %}
            </div>
        {% endfor %}
    </form>

    <p class="body-small on-secondary-container-text">
        Wenn du auch in der Liste stehen willst, kannst du dich <a href="{{path("paypal_add")}}" class="tertiary-text">hier</a> eintragen.
    </p>
{% endblock %}